### ISSUE TITLE
Add server properties file

### ISSUE THREAD

**Issue by arslee07** [mcpyproject/McPy#13]
I think it will be correct if we add a file in which it will be possible to change the properties of the server, for example, its port, the maximum number of players, etc.

**Comment by tazz4843** [comment]
Will be done once fundamental parts of the server (threading, networking, etc) are all working properly.

**Comment by ghost** [comment]
Exceedingly useful module which you should absolutely use to do this https://pypi.org/project/toml/

(if you don't want it to be strictly compatible with the original server)

**Comment by randomairborne** [comment]
I could make a GUI to set this up
