### ISSUE TITLE
Server software is "null"

### ISSUE THREAD

**Issue by tazz4843** [mcpyproject/McPy#15]
https://cdn.discordapp.com/attachments/729914898607243337/741775653921357884/unknown.png

**Comment by ntoskrnl4** [comment]
Looks like this uses the `minecraft:brand` plugin channel... this might require additional logic on the server side to allow plugin channels to be registered. https://wiki.vg/Plugin_channels#minecraft:brand

**Comment by tazz4843** [comment]
It'll have to be done anyways at some point, so might as well get a head-start.
