### ISSUE TITLE
Delete startup.py and use setuptools

### ISSUE THREAD

**Issue by 0ddlyoko** [mcpyproject/McPy#51]
Setuptools is a library that allow us (developers) to build, package and distribute Python packages.

I think we should use setuptools to build and distribute McPy to pypi.org (pip)

**Comment by ntoskrnl4** [comment]
How would McPy make sense as a package? It's not a library or anything of sorts, it's its own full standalone program.

**Comment by 0ddlyoko** [comment]
Maybe it's not a library but at least you can install it using pip and it will automatically install required libraries

**Comment by Geolykt** [comment]
At the very best only the plugin API should be included

**Comment by hydrostaticcog** [comment]
I think we need to focus on getting McPy more new-user friendly. Maybe we just have people download a .zip of the source code and have them run a "dependencies.py"-like program, or we have a setuptools/PyPi.org type thing. I will start looking into both solutions and get back soon with more info.

**Comment by hydrostaticcog** [comment]
I have aimed to fix this with #53. Its not as far as creating a package with setuptools, but it creates an easier way to install dependencies, etc.

**Comment by hydrostaticcog** [comment]
Startup.py was removed in PR #53.
