### ISSUE TITLE
multiprocessing.Queue max_size limited to 32767 on macOS

### ISSUE THREAD

**Issue by ntoskrnl4** [mcpyproject/McPy#52]
On macOS platforms, the maximum allowable size of a `multiprocessing.Queue` is 32767.

A check should probably be added for this in NetworkController (`classes/network/Connection.py`) before the creation of `OUT_QUEUE`.

https://discord.com/channels/729914898607243334/729914898607243337/787017743878193232

---

e: wait I think I goofed

**Comment by Geolykt** [comment]
Also for the future, you might not want to post links for people that do not or refuse to have discord.
On that note I should also note that I quit using discord, so don't expect me to react on anything, but I'll still be here on github

**Comment by hydrostaticcog** [comment]
From my testing on MacOS systems, this bug causes a fatal error, so we need to patch it to add support for MacOS systems.
