### ISSUE TITLE
Am I going Insane?!?

### ISSUE THREAD

**Issue by nonetrix** [mcpyproject/McPy#55]
I wanted to change this message in main.py just as a test

    [2021-01-19 21:35:11,815 - INFO - MainThread] Trying to initialize the Blackfire probe

so I edited this line:
    logging.info("Trying to initialize the Blackfire probe")

and changed it to 
    logging.info("Trrying to initialize the Blackfire probe")

and it did nothing?! even check sure it was saved and opened it in nano instead of vscode and it was changed but it still does nothing

even commented it out then rebooted still nothing I can't change anything..? I want to try adding new features since the code base is small enough for me to understand

**Comment by nonetrix** [comment]
even opened in nano to check if it really saved and it did

**Comment by hydrostaticcog** [comment]
I'm not sure what your problem is. If you are wondering what the black fire probe is, I don't know what it does, other than it's not required to run the program.

**Comment by nonetrix** [comment]
I think I may have figured it out I'll report back

**Comment by nonetrix** [comment]
I have added a lot of print statements in main.py only one that seems to work is the one at the top sorry if I am doing something wrong I am not very good at this

**Comment by hydrostaticcog** [comment]
The actual code is in classes, so putting things in main.py would most likely not do anything. I’m not sure how much of this can be fixed via an issue here though, since it sounds like this is an issue on your end and no one else seems to be having the same issue.

**Comment by nonetrix** [comment]
I don't know much about classes sorry I I'll look into it ;-;

**Comment by Geolykt** [comment]
He is meaning the folder "classes" with classes

**Comment by DevBennyturtle** [comment]
this github is no longer being updated anyway, i recommend checking out mine which I will be more active in
http://github.com/pamcpy/pamcpy

**Comment by ntoskrnl4** [comment]
> this github is no longer being updated anyway, i recommend checking out mine which I will be more active in
> 
> http://github.com/pamcpy/pamcpy

You don't need to create your own fork in order to develop the code, in fact, I'd recommend against it. The fact that no one has committed to this repo in a little bit should encourage you to commit here, not make your own fork. This is an open source project, not a forum thread where you have to make a new one if it goes inactive.

**Comment by ntoskrnl4** [comment]
(I would have tagged this issue as off-topic but it seems I've lost the ability to manage issues/PRs.)

**Comment by DevBennyturtle** [comment]
well there are only like 1-3 people here who still have write access to this github, and i dont want to wait forever for stuff to get merged if i am the only one active in it

**Comment by ntoskrnl4** [comment]
That's fair, but keep in mind we all have lives so we can't get around to everything immediately.

The PR you submitted to this repository has problems as we already described in #54. It will almost certainly be reviewed and approved once you correct that.

**Comment by DevBennyturtle** [comment]
I know you have lives, and the PR i submitted was a long time ago.
I am already rewriting the entire project from the ground up. 
this is also GitHub, so we are free to do what we want as long as it doesn't violate the law
but lets just agree to disagree

**Comment by Geolykt** [comment]
> (I would have tagged this issue as off-topic but it seems I've lost the ability to manage issues/PRs.)

it appears that almost everyone has lost that right in the migration, which basically deadlocks the whole project due to no PR being acceptable

**Comment by hydrostaticcog** [comment]
If no one can do anything in the repo, what should we do about that?

**Comment by tazz4843** [comment]
Just looked into it, turns out when 0ddly moved the repo to a team, it kinda broke permissions. I've invited @Geolykt and @ntoskrnl4 back, if anyone else needs a invite let me know.
